language: java
os: linux
dist: trusty
jdk: oraclejdk8
git:
  depth: false

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/build/distributions/"
  - "$HOME/release/"

before_install: git submodule update --init --recursive

install: echo "Ready to Build Thermos!"

before_script: 
 - find .
 - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

jobs:
  include:
  - # Build debug
    if: branch IN (develop, master)
    script: "./travii/make.sh"
  - # Build and deploy release on tags
    if: tag IS present
    script: "./travii/make.sh"
    deploy:
      provider: releases
      token:
        secure: bs4gTXJqghp0LnfXiIMStG82C6NtIZWTuTHkVY+lSz0ktMSnIoLmq8YkRQooxThIHH3g9GIDZE/nCEW6wHetlkLTemrLyjIEdRmVXF13brBQv8W8J6v/o/n8qGqoEqi6AfHgsRNuBF1UqQppq8Li0VSfx4CIebipsfv7l8qycJqS76BSVfO2Z+yPL41F4Gy3JHq5ntPI6BzM6pwi3xlw0xUovvSCn4IGDPtavG4FfA6VwfU1Tbq6pg072pEzU1j2vopiMO0kKHZnJm7ZgWKz6HSP76jThkyhg+C8GNZl0MtUSJiEh8A1oLQm0nrtAesuMfznby56I1yp6o2lL7erT+Fy3eoBZlFZMS2KVHVkFjuDJU66mlSNJpRsHsXZwLsjscS9buRd4z2D+9aRmOm1r3n2dclQw2z7QZgNJXJNCGj8cFBo/IqStiuGVQwCCHGD/9713v0VeNnA/qcbVecsT9I4DyKvD6w+eevvwYq2bPX/8Pz/dtot/M8ZUbwlfDiu+Ulwzz0QMfX0kvp/nCUGd5HNN2TmfojCwJSV+eLCs2HEseEo1fwed5uQo7cm+Ccact8pb2mQxEUnU+VHiczW1BLBAQTB3sX47K2UU7YunCxlWnLCAksoSI2GACar1PVW3F/FXdygsFo0qamGsu11xac4KbIMV189NcUZF3vqo60=
      file_glob: true
      file: "$HOME/release/*"
      skip_cleanup: true
      draft: false
      on:
        repo: MCImaginarium/Thermos
        tags: yes